- id: clear-notebook-outputs
  name: clear notebook outputs
  description: clear outputs from jupyter notebooks
  entry: clear-notebook-outputs.sh
  language: script
  types: [jupyter]
- id: check-notebook-sources
  name: check notebook sources
  description: check sources from jupyter notebooks
  entry: check-notebook-sources.sh
  language: script
  types: [jupyter]
